# ==================================================
# Seeking
# ==================================================

WHEEL_UP seek 2
WHEEL_DOWN seek -2

# ==================================================
# Volume
# ==================================================

ALT+WHEEL_UP add volume 2
ALT+WHEEL_DOWN add volume -2

# ==================================================
# Zoom
# ==================================================

CTRL+WHEEL_UP add video-zoom 0.05
CTRL+WHEEL_DOWN add video-zoom -0.05

# ==================================================
# Playlist
# ==================================================

SHIFT+WHEEL_UP playlist-prev
SHIFT+WHEEL_DOWN playlist-next
