# ==================================================
# Window
# ==================================================

autofit=50%x50%

# ==================================================
# Interface
# ==================================================

osc=no
title-bar=no

# ==================================================
# Audio
# ==================================================

volume=15
volume-max=150

# ==================================================
# Playback
# ==================================================

save-position-on-quit=yes
save-watch-history=yes

loop-file=inf

autocreate-playlist=same
directory-mode=ignore

# ==================================================
# Seeking
# ==================================================

hr-seek=yes

# ==================================================
# Hardware Decode
# ==================================================

hwdec=auto-safe

# ==================================================
# Reset State
# ==================================================

reset-on-next-file=window-scale,video-zoom,video-rotate,video-align-x,video-align-y,video-aspect-override,video-pan-x,video-pan-y,panscan,vf
