#!/usr/bin/env bash

set -e

STATE="$HOME/.local/state/current-theme"

mkdir -p "$(dirname "$STATE")"

echo vintage > "$STATE"

generate-theme

pkill waybar || true
waybar >/dev/null 2>&1 &

wallpaper

pkill wallpaperd || true
wallpaperd >/dev/null 2>&1 &
