[General]
JPEGSaveQuality=95

autoResizeWindow=false
autoResizeLimit=60

backgroundOpacity=0.75
blurBackground=true

defaultFitMode=0
keepFitMode=false

expandImage=false
expandLimit=2

infoBarFullscreen=true
infoBarWindowed=false

panelEnabled=false
panelFullscreenOnly=true
panelPinned=false

cursorAutohiding=true

enableSmoothScroll=true
smoothUpscaling=true
smoothAnimatedImages=true
unlockMinZoom=true

focusPointIn1to1Mode=1

memoryAllocationLimit=8192
thumbnailCache=true
thumbnailerThreads=4
usePreloader=true

videoPlayback=true
playVideoSounds=false

windowTitleExtendedInfo=true
zoomIndicatorMode=0
zoomStep=0.20
