#!/usr/bin/env bash

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Rainier Change Preview"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

echo "Building preview generation..."
echo

sudo nixos-rebuild build

echo
echo "Comparing generations..."
echo

nvd diff /run/current-system result
