#!/usr/bin/env bash

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Rainier Upgrade"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

echo "Updating channels..."
sudo nix-channel --update

echo
echo "Building and activating system..."
echo

sudo nixos-rebuild switch

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Updated Packages"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

nvd diff /nix/var/nix/profiles/system-1-link /run/current-system || true

echo
echo "Current version:"
echo "$(nixos-version)"
echo

echo "✓ Upgrade complete."
